--CREATE VIEW MM_KISAVEIKKAUS.MIKA_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.ALEKSIOJA_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.ANNA_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.ASM_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.DIMA_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.OTSO_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.JUHANI_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.KAAREL_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.KALLE_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.KIMMO_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.LARS_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.LIISA_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.RASMUS_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS
--CREATE VIEW MM_KISAVEIKKAUS.TUOMAS_MM_KISAVEIKKAUS_MATCHES_V (id, points) AS

SELECT 

      id
    , sum(final_points) as points
    
  FROM (

    SELECT 

             r.id
           , r.match
           , r.home_team_goals AS home_team_goals_final
           , r.away_team_goals AS away_team_goals_final
           , CASE WHEN TO_NUMBER(TRIM(r.home_team_goals)) > TO_NUMBER(TRIM(r.away_team_goals)) THEN 'HOME' ELSE 'AWAY' END AS R_WINNER
           , p.home_team_goals
           , p.away_team_goals
           , CASE WHEN TO_NUMBER(TRIM(p.home_team_goals)) > TO_NUMBER(TRIM(p.away_team_goals)) THEN 'HOME' ELSE 'AWAY' END AS P_WINNER
           , CASE WHEN TO_NUMBER(TRIM(p.home_team_goals)) = TO_NUMBER(TRIM(r.home_team_goals)) 
                   AND TO_NUMBER(TRIM(p.away_team_goals)) = TO_NUMBER(TRIM(r.away_team_goals)) THEN 3 ELSE 0 END AS MATCH_POINTS
           , CASE WHEN R_WINNER = P_WINNER THEN 1 ELSE 0 END AS WINNER_POINTS
           , CASE WHEN MATCH_POINTS > WINNER_POINTS THEN MATCH_POINTS ELSE WINNER_POINTS END AS FINAL_POINTS
     
      FROM MM_KISAVEIKKAUS.MM_KISAVEIKKAUS_RESULTS r
     INNER JOIN MM_KISAVEIKKAUS.LERSSI_MM_KISAVEIKKAUS p ON r.id = p.id
     WHERE r.home_team_goals IS NOT NULL
       AND r.match IS NOT NULL

    )

 GROUP BY ROLLUP (id)
